# site properties and page defaults
title: Climate Data and Dynamics Lab
subtitle: based in Sydney, Australia.
description: Welcome to the Climate Data and Dynamics Lab! We are a team of data scientists and physicists using a range of tools from cutting edge statistics to process driven dynamical models to understand the ocean and climate.
header: images/NASA-Scientific-Visual-Studio-Ocean-Currents-Maps.png
footer: images/NASA-Scientific-Visual-Studio-Ocean-Currents-Maps.png

# site social media and other links
links:
  email: j.zika@unsw.edu.au
  orcid: 0000-0003-3462-3559
  google-scholar: 0pFeyJQAAAAJ
  github: Climate-Data-Dynamics
  twitter: JanDZika
  #youtube: Climate-Data-Dynamics

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  #- scope:
  #    type: "posts"
  #  values:
  #    layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
