- id: doi:10.1175/jpo-d-22-0145.1
  image: https://drive.google.com/uc?export=view&id=195oOwUL2F1v-qMn2hJj4_yBYGKF9u6nL
- id: doi:10.1175/jcli-d-22-0267.1
  image: https://drive.google.com/uc?export=view&id=1-2AbdqgUMxde0iqEOWxCqOHmZcMgm9vf
- id: doi:10.1016/B978-0-12-821512-8.00010-4
  image: https://drive.google.com/uc?export=view&id=1-FhTnp3J2JLc5uO_8axU7grYtaYdU-4u
- id: doi:10.1029/2020gl091439
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/3900130c-c675-4b88-93a6-d1f3cc097d1c/grl62254-fig-0004-m.jpg
- id: doi:10.1038/s41586-021-04370-w
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-021-04370-w/MediaObjects/41586_2021_4370_Fig2_HTML.png?as=webp
- id: doi:10.1175/jcli-d-21-0695.1
  image: https://journals.ametsoc.org/view/journals/clim/35/5/full-JCLI-D-21-0695.1-fA1.jpg
- id: doi:10.1175/jcli-d-22-0363.1
  image: https://journals.ametsoc.org/view/journals/clim/36/9/full-JCLI-D-22-0363.1-f2.jpg
- id: doi:10.1029/2020GL089455
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/8e000b8a-f1d7-4784-9462-05736b339a09/grl61613-fig-0001-m.jpg
- id: doi:10.1175/jpo-d-19-0264.1
  image: https://journals.ametsoc.org/view/journals/phoc/50/6/full-JPO-D-19-0264.1-f1.jpg
- id: doi:10.1029/2018jc014883
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/8e6aeeeb-6fed-49fe-8c8a-6cc1caf0a86c/jgrc23463-fig-0001-m.jpg
- id: doi:10.1029/2018GL077711
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/bcdbbe4d-96ae-46f5-a0f0-def70c529fb0/grl57301-fig-0001-m.jpg
- id: doi:10.1175/jcli-d-21-0793.1
  image: https://journals.ametsoc.org/view/journals/clim/35/15/full-JCLI-D-21-0793.1-fA1.jpg
- id: doi:10.3389/fclim.2022.861477
  image: https://www.frontiersin.org/files/Articles/861477/fclim-04-861477-HTML-r3/image_m/fclim-04-861477-g002.jpg
- id: doi:10.1029/2020ms002333
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/5aed27fb-ca2c-4aaa-a34d-9aa706d14dcc/jame21392-fig-0001-m.jpg
- id: doi:10.1175/jpo-d-21-0008.1
  image: https://journals.ametsoc.org/view/journals/phoc/51/8/full-JPO-D-21-0008.1-f1.jpg
- id: doi:10.1175/jcli-d-20-0355.1
  image: https://journals.ametsoc.org/view/journals/clim/34/9/full-JCLI-D-20-0355.1-f1.jpg
- id: doi:10.1175/jpo-d-20-0212.1
  image: https://journals.ametsoc.org/view/journals/phoc/51/7/full-JPO-D-20-0212.1-f7.jpg
- id: doi:10.1175/jcli-d-20-0625.1
  image: https://journals.ametsoc.org/view/journals/clim/34/7/full-JCLI-D-20-0625.1-f9.jpg
- id: doi:10.1029/2020GL089455
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/0c55a4b0-b3de-40e9-92a4-8d1b53ccadcb/grl61613-fig-0001-m.jpg
- id: doi:10.1175/jcli-d-20-0281.1
  image: https://journals.ametsoc.org/view/journals/clim/34/8/full-JCLI-D-20-0281.1-f1.jpg
- id: doi:10.1175/jcli-d-19-0579.1
  image: https://journals.ametsoc.org/view/journals/clim/33/15/full-jcliD190579-f8.jpg
- id: doi:10.1175/jpo-d-19-0188.1
  image: https://journals.ametsoc.org/view/journals/phoc/50/6/full-JPO-D-19-0188.1-f2.jpg
- id: doi:10.1007/s00382-020-05261-y
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1007%2Fs00382-020-05261-y/MediaObjects/382_2020_5261_Fig3_HTML.png?as=webp
- id: doi:10.1038/s41467-020-15754-3
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-020-15754-3/MediaObjects/41467_2020_15754_Fig1_HTML.png?as=webp
- id: doi:10.5194/os-16-323-2020
  image: https://os.copernicus.org/articles/16/323/2020/os-16-323-2020-avatar-web.png
- id: doi:10.1098/rsta.2022.0056
  image: https://royalsocietypublishing.org/cms/asset/bb8669e8-9246-4a7b-be9a-734329364da3/rsta20220056f02.gif
- id: doi:10.1029/2019gl085160
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/01921136-abc8-4193-8d2b-6d6106be2a3c/grl59797-fig-0001-m.jpg
- id: doi:10.1175/jpo-d-19-0139.1
  image: https://journals.ametsoc.org/view/journals/phoc/49/8/inline-jpo-d-19-0139.1-f1.jpg
- id: doi:10.1146/annurev-marine-010318-095421
  image: https://www.annualreviews.org/na101/home/literatum/publisher/ar/journals/content/marine/2019/marine.2019.11.issue-1/annurev-marine-010318-095421/20181116/images/medium/ma110271.f1.gif
- id: doi:10.1175/JPO-D-18-0098.1
  image: https://journals.ametsoc.org/view/journals/phoc/49/1/full-jpo-d-18-0098.1-f1.jpg
- id: doi:10.1029/2018GL079986
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/6413c723-0ba9-45e2-aeb4-d57291e55d1f/grl58376-fig-0001-m.jpg
- id: doi:10.1175/JTECH-D-17-0198.1
  image: https://journals.ametsoc.org/view/journals/atot/35/12/inline-jtech-d-17-0198.1-f3.jpg
- id: doi:10.1088/1748-9326/aace42
  image: https://cfn-live-content-bucket-iop-org.s3.amazonaws.com/journals/1748-9326/13/7/074036/revision2/erlaace42f4_online.jpg?AWSAccessKeyId=AKIAYDKQL6LTV7YY2HIK&Expires=1692418816&Signature=%2BgaEB0nCHJQt2VyB2jAaUuc3s%2B8%3D
- id: doi:10.1007/s00382-017-4053-7
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1007%2Fs00382-017-4053-7/MediaObjects/382_2017_4053_Fig1_HTML.gif?as=webp
- id: doi:10.1002/2017GL075182
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/4d0ebc30-518f-465f-8a4b-7fc32908f052/grl56476-fig-0003-m.jpg
- id: doi:10.1098/rsta.2016.0324
  image: https://royalsocietypublishing.org/cms/asset/1bd8f99d-794c-4eb1-921d-8ecbdf30002d/rsta20160324f01.jpg
- id: doi:10.1175/BAMS-D-16-0057.1
  image: https://journals.ametsoc.org/view/journals/bams/98/4/inline-bams-d-16-0057.1-f1.jpg
- id: doi:10.1175/jpo-d-16-0089.1
  image: https://journals.ametsoc.org/view/journals/phoc/47/3/inline-jpo-d-16-0089.1-f3.jpg
- id: doi:10.1175/jpo-d-16-0125.1
  image: https://journals.ametsoc.org/view/journals/phoc/47/3/inline-jpo-d-16-0125.1-f4.jpg
- id: doi:10.1175/JCLI-D-15-0759.1
  image: https://journals.ametsoc.org/view/journals/clim/30/2/inline-jcli-d-15-0759.1-f8.jpg
- id: doi:10.1038/srep38752
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fsrep38752/MediaObjects/41598_2016_Article_BFsrep38752_Fig1_HTML.jpg?as=webp
- id: doi:10.1002/2016JC012091
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/23b94c60-2ccb-4c3b-b5b8-f018a7ad33a6/jgrc22017-fig-0002-m.jpg
- id: doi:10.1002/2015GL066658
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/a6e0c558-b5e5-4fa3-9039-724ddad8727e/grl53879-fig-0003-m.jpg
- id: doi:10.1175/JPO-D-15-0025.1
  image: https://journals.ametsoc.org/view/journals/phoc/46/1/inline-jpo-d-15-0025.1-f1.jpg
- id: doi:10.1175/JCLI-D-15-0273.1
  image: https://journals.ametsoc.org/view/journals/clim/28/24/inline-jcli-d-15-0273.1-f1.jpg
- id: doi:10.1002/2015GL064156
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/cada7554-84a5-4d3e-a226-f8ef28846a15/grl53026-fig-0002-m.jpg
- id: doi:10.1175/JPO-D-14-0053.1
  image: https://journals.ametsoc.org/view/journals/phoc/45/4/inline-jpo-d-14-0053.1-f4.jpg
- id: doi:10.1002/2014JC010097
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/03bfc435-03ca-4fe5-9921-0f3a47e8e9a2/jgrc20971-fig-0003-m.jpg
- id: doi:10.1175/JPO-D-14-0039.1
  image: https://journals.ametsoc.org/view/journals/phoc/44/10/inline-jpo-d-14-0039.1-f6.jpg
- id: doi:10.1175/JPO-D-13-0213.1
  image: https://journals.ametsoc.org/view/journals/phoc/44/7/inline-jpo-d-13-0213.1-f10.jpg
- id: doi:10.1175/JAS-D-13-0173.1
  image: https://journals.ametsoc.org/view/journals/atsc/71/3/inline-jas-d-13-0173.1-f1.jpg
- id: doi:10.1016/j.ocemod.2017.11.008
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1463500317301853-gr4.jpg
- id: doi:10.1175/JPO-D-13-091.1
  image: https://journals.ametsoc.org/view/journals/phoc/43/12/full-jpo-d-13-091.1-f5.jpg
- id: doi:10.1007/s00382-013-1992-5
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1007%2Fs00382-013-1992-5/MediaObjects/382_2013_1992_Fig1_HTML.gif?as=webp
- id: doi:10.1175/JPO-D-12-0179.1
  image: https://journals.ametsoc.org/view/journals/phoc/43/10/inline-jpo-d-12-0179.1-f3.jpg
- id: doi:10.1175/JPO-D-12-0178.1
  image: https://journals.ametsoc.org/view/journals/phoc/43/5/inline-jpo-d-12-0178.1-f2.jpg
- id: doi:10.1175/JCLI-D-11-00309.1
  image: https://journals.ametsoc.org/view/journals/clim/25/20/inline-jcli-d-11-00309.1-f1.jpg
- id: doi:10.1175/JPO-D-11-0139.1
  image: https://journals.ametsoc.org/view/journals/phoc/42/5/inline-jpo-d-11-0139.1-f8.jpg
- id: doi:10.1029/2012GL051004
  image: https://agupubs.onlinelibrary.wiley.com/cms/asset/3763f7a6-ce23-471b-ac6e-a69577cd2bd9/grl29008-fig-0002.png
- id: doi:10.1175/JCLI-D-11-00077.1
  image: https://journals.ametsoc.org/view/journals/clim/24/21/inline-jcli-d-11-00077.1-f9.jpg
- id: doi:10.1175/2010JPO4360.1
  image: https://journals.ametsoc.org/view/journals/phoc/40/8/inline-i1520-0485-40-8-1881-f02.jpg
- id: doi:10.1175/2009JPO4208.1
  image: https://journals.ametsoc.org/view/journals/phoc/40/1/inline-i1520-0485-40-1-26-f02.jpg
- id: doi:10.1175/2009JPO4052.1
  image: https://journals.ametsoc.org/view/journals/phoc/39/11/inline-i1520-0485-39-11-2926-f02.gif
- id: doi:10.1175/2007JPO3507.1
  image: https://journals.ametsoc.org/view/journals/phoc/38/1/inline-i1520-0485-38-1-164-f01.gif
- id: doi:10.1038/s43017-022-00345-1
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs43017-022-00345-1/MediaObjects/43017_2022_345_Fig2_HTML.png?as=webp