name: build-preview
run-name: Build pull request preview

on:
  # called from on-pull-request
  workflow_call:

permissions:
  contents: read

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch contents
        if: github.event.action != 'closed'
        # checks out potentially untrusted code
        uses: actions/checkout@v7
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Install Ruby packages
        if: github.event.action != 'closed'
        # runs potentially untrusted code
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Get Pages URL
        if: github.event.action != 'closed'
        id: pages
        uses: actions/configure-pages@v6

      - name: Build preview version of site
        if: github.event.action != 'closed'
        # runs potentially untrusted code
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}/preview/pr-${{ github.event.number }}"

      - name: Save preview artifact
        run: |
          mkdir -p artifacts
          # save metadata about preview
          printf "%s" "${{ github.event.number }}" > artifacts/number.txt
          printf "%s" "${{ github.event.action }}" > artifacts/action.txt
          # save built preview contents
          if [ -d _site ]; then mv _site artifacts/preview; fi

      # safely save limited artifact from potentially untrusted branch
      - name: Upload preview artifact
        uses: actions/upload-artifact@v7
        with:
          name: preview
          path: artifacts
          retention-days: 1
